version: "3.8"

services:
  # PHP/Apache側
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # MySQL側
  db:
    image: mysql:8.0 # 8.0系を指定
    container_name: seiji-mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
