version: "3.8"

services:
  # PHP/Apache側
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # MySQL側
  db:
    image: mysql:5.7 # PHP 7.2なら5.7あたりが安定します
    platform: linux/amd64 # M1/M2 Macなどの場合はこれが必要
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
